### ISSUE TITLE
Failing login

### ISSUE THREAD

**Issue by messa** [messa/pyladies-courseware#115]
I cannot log in. I think my session db record has expired and the session library does not renew the db record (there is just "update" instead of "upsert").

**Comment by messa** [comment]
Removing the cookie in the browser settings solves the issue for given user. But still a bug in the session db code.

**Comment by messa** [comment]
What? :)

```
2020-01-18 12:59:36,191 aiohttp_session_mongo           DEBUG: [load_session] find_one(_id: b'AIOHTTP_SESSION_327REDACTEDa28') -> {'_id': b'AIOHTTP_SESSION_327REDACTEDa28', 'data': {'created': 1566820929, 'session': {'user': None, 'oauth2_state': 'A8bPREDACTEDHBfs'}}, 'expire': datetime.datetime(2020, 4, 17, 12, 39, 52, 704000)}
2020-01-18 12:59:36,193 aiohttp.server                  ERROR: Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp_session/__init__.py", line 154, in factory
    response = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/cw_backend/views/auth.py", line 221, in google_callback
    if req.query['state'] != session['oauth2_state']:
  File "/usr/local/lib/python3.7/site-packages/aiohttp_session/__init__.py", line 94, in __getitem__
    return self._mapping[key]
KeyError: 'oauth2_state'
```

**Comment by messa** [comment]
This is weird:

```
2020-01-18 13:25:42,112 aiohttp_session_mongo           DEBUG: [Session] args=('327REDACTEDa28',) kwargs={'data': {'created': 1566820929, 'session': {'user': None, 'oauth2_state': 'A8bREDACTEDBfs'}}, 'new': False, 'max_age': 7776000}
2020-01-18 13:25:42,112 aiohttp_session_mongo           DEBUG: [Session] _mapping={}
```

(I've added logging to the Session class, see https://github.com/messa/aiohttp-session-mongo/commit/c7538b772ee1693854e954e56548bc1b7bfeb495)

**Comment by messa** [comment]
Source code of Session constructor directly from Docker container:

```python
class Session(MutableMapping):

    """Session dict-like object."""

    def __init__(self, identity, *, data, new, max_age=None):
        self._changed = False
        self._mapping = {}
        self._identity = identity if data != {} else None
        self._new = new
        self._new = new if data != {} else True
        self._max_age = max_age
        created = data.get('created', None) if data else None
        session_data = data.get('session', None) if data else None
        now = int(time.time())
        age = now - created if created else now
        if max_age is not None and age > max_age:
            session_data = None
        if self._new or created is None:
            self._created = now
        else:
            self._created = created

        if session_data is not None:
            self._mapping.update(session_data)
```

**Comment by messa** [comment]
It's probably because `age > max_age` 

```python
>>> datetime.utcfromtimestamp(1566820929)
datetime.datetime(2019, 8, 26, 12, 2, 9)
>>> datetime.utcfromtimestamp(1566820929 + 7776000)
datetime.datetime(2019, 11, 24, 12, 2, 9)
>>> datetime.utcnow()
datetime.datetime(2020, 1, 18, 13, 33, 2, 549738)
```

**Comment by messa** [comment]
It's probably this issue: https://github.com/aio-libs/aiohttp-session/issues/344

Caused by this PR: https://github.com/aio-libs/aiohttp-session/pull/331

**Comment by messa** [comment]
In the meantime, **hotfix** is to clear browser cookie.
